# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#> .

`Acme-Constructor-Pythonic`
	:test-requirement    [ :on "Test::More 0.61"^^:CpanId ];
	:test-recommendation [ :on "Moose 2.0600"^^:CpanId ];
	:test-recommendation [ :on "Sub::Identify"^^:CpanId ];
	:runtime-requirement [ :on "Module::Runtime"^^:CpanId ];
	:runtime-requirement [ :on "Exporter::Tiny"^^:CpanId ].
	.

